Repository yalla-coop/rent-check, pull requests merged in 2019-10, with the labels that each got.

#65 remove landing route and replace with map route
  src/components/Common/Nav/index.js
  src/constants/navRoutes.js
Labels: awaiting-review

#58 create addLocation endpoint, clean up lambda files
  src/constants/rentalRecords.js
  src/lambda/addLocation.js
  src/lambda/database/queries/rentalRecord/index.js
  src/lambda/database/queries/user/index.js
  src/lambda/getLocations.js
  src/lambda/getUsers.js
  src/lambda/models/getRecords.js
  src/lambda/models/getRecords.test.js
  src/lambda/models/postcodes.js
  src/lambda/models/postcodes.test.js
  src/lambda/models/updateRecords.js
  src/lambda/models/updateRecords.test.js
  src/lambda/utils/postcodes.js
Labels: awaiting-review

#66 Rental data form
  .eslintrc.js
  package-lock.json
  package.json
  src/components/Admin/Users/index.js
  src/components/MapInterface/index.js
  src/components/RentalForm/FormItem.js
  src/components/RentalForm/RentalForm.style.js
  src/components/RentalForm/index.js
  src/components/RentalForm/inputTypes/DatePicker.js
  src/components/RentalForm/inputTypes/NumberInput.js
  src/components/RentalForm/inputTypes/Select.js
  src/components/RentalForm/inputTypes/Text.js
  src/components/RentalForm/inputTypes/Textarea.js
  src/components/RentalForm/inputTypes/index.js
  src/components/RentalForm/rental-form.config.js
  src/components/RentalForm/rentalForm.validation.js
  src/components/index.js
  src/constants/rentalRecords.js
  src/hooks/useFetch.js
  src/hooks/useForm.js
  src/hooks/usePost.js
  src/lambda/addLocation.js
  src/lambda/database/models/RentalRecord.js
  src/lambda/database/queries/rentalRecord/index.js
  src/lambda/utils/validation.js
Labels: awaiting-review

#74 link button to form > #73
  src/components/MapMarkers/index.js
Labels: awaiting-review

#85 fix update user status
  src/components/Admin/Users/AllUsers.js
Labels: awaiting-review, priority-1

#79 15 admin add rental record
  package-lock.json
  package.json
  src/components/Admin/RentalData/AddedByAdmin/index.js
  src/components/Admin/RentalData/AddedByAdmin/tableColumns.js
  src/components/Admin/RentalData/dummyData.js
  src/components/Admin/Table.js
  src/components/Admin/adminRoutes.js
  src/components/Admin/index.js
  src/constants/adminRoutes.js
  src/hooks/useForm.js
  src/lambda/addLocation.js
  src/lambda/database/queries/rentalRecord/index.js
  src/lambda/getRentalRecordAddedByAdmin.js
Labels: approved

#83 Update rental Records db model + large set of rental dummy data
  package-lock.json
  package.json
  src/components/Map/Map.test.js
  src/components/MapMarkers/index.js
  src/lambda/database/data/fakedata.js
  src/lambda/database/data/postcodes.csv
  src/lambda/database/data/postcodes3000dup.csv
  src/lambda/database/data/rentalRecords.js
  src/lambda/database/dbConnection.js
  src/lambda/database/models/RentalRecord.js
  src/lambda/database/queries/rentalRecord/index.js
Labels: approved

#92 fix eslint setup + remove extra dependencies
  .eslintrc.js
  client/.babelrc
  client/package-lock.json
  client/package.json
  package-lock.json
  package.json
  server/index.js
  server/package-lock.json
  server/package.json
Labels: awaiting-review

#89 44 request super
  .eslintrc.js
  client/src/components/Common/Nav/index.js
  client/src/components/StreetReps/index.js
  client/src/components/index.js
  client/src/constants/navRoutes.js
  server/controllers/index.js
  server/controllers/reps/getReps.js
  server/controllers/reps/handleStreetRepRequest.js
  server/controllers/reps/index.js
  server/database/queries/user/getAllSuperUsers.js
  server/database/queries/user/getAllSuperUsers.test.js
  server/database/queries/user/index.js
  server/database/queries/user/requestSuperUser.js
  server/database/queries/user/requestSuperUser.test.js
Labels: awaiting-review

#90 18 superuser manage data
  .eslintrc.js
  client/package-lock.json
  package-lock.json
  package.json
  server/controllers/index.js
  server/controllers/locations/getSuperUserRecords.js
  server/controllers/locations/index.js
  server/database/queries/rentalRecord/getRentalRecordsByIds.js
  server/database/queries/user/getSuperUserSubUsers.js
  server/package-lock.json
  server/package.json
  server/utils/isValidMongoID.js
Labels: awaiting-review
