Repository yalla-coop/rent-check, pull requests merged in 2019-09, with the labels that each got.

#33 Mongodb setup
  .babelrc
  .eslintrc
  .eslintrc.js
  package-lock.json
  package.json
  src/components/App/App.test.js
  src/components/App/index.js
  src/components/Header/index.js
  src/components/Map/Map.js
  src/lambda/database/data/index.js
  src/lambda/database/data/users.js
  src/lambda/database/dbConnection.js
  src/lambda/database/models/users.js
  src/lambda/database/resetDb.js
  src/lambda/getLocations.js
  src/lambda/getUsers.js
  src/lambda/models/getRecords.js
  src/lambda/models/getRecords.test.js
  src/lambda/models/postcodes.js
  src/lambda/models/updateRecords.js
  src/lambda/protected.js
  src/lambda/utils/auth.js
  src/lambda/utils/middleware.js
  src/setupProxy.js
Labels: awaiting-review

#46 Refactor App to bring in Router and set up Admin control panel setup
  .eslintrc.js
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/Admin/Admin.style.js
  src/components/Admin/Dashboard/Dashboard.style.js
  src/components/Admin/Dashboard/index.js
  src/components/Admin/RentalData/RentalData.style.js
  src/components/Admin/RentalData/dummyData.js
  src/components/Admin/RentalData/index.js
  src/components/Admin/RentalData/rentalDataColumns.js
  src/components/Admin/SideMenu/SideMenu.style.js
  src/components/Admin/SideMenu/index.js
  src/components/Admin/Table.js
  src/components/Admin/Users/Users.style.js
  src/components/Admin/Users/UsersColumns.js
  src/components/Admin/Users/dummyUsers.js
  src/components/Admin/Users/index.js
  src/components/Admin/index.js
  src/components/Loading/Loading.styles.js
  src/components/Loading/Loading.test.js
  src/components/Loading/index.js
  src/components/MapInterface/MapInterface.style.js
  src/components/MapInterface/MapInterface.test.js
  src/components/MapInterface/index.js
  src/components/PostcodeForm/index.js
  src/components/index.js
  src/constants/adminRoutes.js
  src/index.js
  src/tachyons.css
Labels: in-review

#47 Update database and build schemas
  .eslintrc.js
  .travis.yml
  .vscode/settings.json
  package.json
  src/__mocks__/request.js
  src/__tests__/database/dummyData.js
  src/components/Header/Header.styles.js
  src/components/Map/Map.test.js
  src/components/Map/index.js
  src/components/MapMarkers/MapMarkers.styles.js
  src/components/MapMarkers/index.js
  src/constants/rentalRecords.js
  src/constants/users.js
  src/lambda/database/data/index.js
  src/lambda/database/data/rentalRecords.js
  src/lambda/database/data/users.js
  src/lambda/database/dbConnection.js
  src/lambda/database/models/RentalRecord.js
  src/lambda/database/models/User.js
  src/lambda/database/models/users.js
  src/lambda/database/resetDb.js
  src/lambda/getLocations.js
  src/lambda/getUsers.js
Labels: in-review

#50 Eslint autoformat all files
  .eslintrc.js
  package-lock.json
  src/App.js
  src/components/Admin/Dashboard/Dashboard.style.js
  src/components/Admin/SideMenu/index.js
  src/components/Header/Header.test.js
  src/components/Header/index.js
  src/components/Legend/Legend.styles.js
  src/components/Legend/Legend.test.js
  src/components/Legend/index.js
  src/components/Loading/Loading.styles.js
  src/components/Loading/Loading.test.js
  src/components/Loading/index.js
  src/components/Map/Map.js
  src/components/MapInterface/MapInterface.test.js
  src/components/MapInterface/index.js
  src/components/MapMarkers/index.js
  src/components/MarkerIcon.js
  src/components/PostcodeForm/PostcodeForm.styles.js
  src/components/PostcodeForm/PostcodeForm.test.js
  src/components/PostcodeForm/index.js
  src/lambda/database/data/index.js
  src/lambda/database/dbConnection.js
  src/lambda/database/models/User.js
  src/lambda/getUsers.js
  src/lambda/models/getRecords.js
  src/lambda/models/getRecords.test.js
  src/lambda/models/postcodes.js
  src/lambda/models/postcodes.test.js
  src/lambda/models/updateRecords.js
  src/lambda/models/updateRecords.test.js
  src/lambda/protected.js
  src/lambda/utils/middleware.js
  src/serviceWorker.js
  src/setupProxy.js
Labels: awaiting-review

#53 fix vulnerability
  package-lock.json
Labels: awaiting-review

#51 Refactor class components into hooks- Admin panel
  src/App.js
  src/components/Admin/Dashboard/index.js
  src/components/Admin/RentalData/index.js
  src/components/Admin/RentalData/rentalDataColumns.js
  src/components/Admin/SideMenu/index.js
  src/components/Admin/Table.js
  src/components/Admin/Users/index.js
  src/components/Admin/index.js
  src/components/index.js
Labels: awaiting-review

#52 Refactor class components into hooks- the Rest
  .eslintrc.js
  src/components/Header/index.js
  src/components/Legend/Legend.styles.js
  src/components/Legend/index.js
  src/components/Loading/index.js
  src/components/Map/Map.js
  src/components/Map/index.js
  src/components/MapInterface/index.js
  src/components/PostcodeForm/index.js
  src/useFetch.js
Labels: awaiting-review

#55 Update branding
  src/assets/eetg.png
  src/assets/logo.png
  src/components/Header/Header.styles.js
  src/components/PostcodeForm/PostcodeForm.styles.js
Labels: awaiting-review

#39 Add common components #34
  src/App.js
  src/components/Admin/Admin.style.js
  src/components/Admin/index.js
  src/components/Common/Button/index.js
  src/components/Common/Nav/Nav.style.js
  src/components/Common/Nav/index.js
  src/components/Header/Header.styles.js
  src/components/Header/Header.test.js
  src/components/Header/index.js
  src/components/MapInterface/index.js
  src/components/index.js
  src/constants/breakpoints.js
  src/constants/navRoutes.js
Labels: awaiting-review

#56 View all users #6
  package-lock.json
  src/__tests__/database/getUsers.js
  src/components/Admin/SideMenu/index.js
  src/components/Admin/Users/UsersColumns.js
  src/components/Admin/Users/dummyUsers.js
  src/components/Admin/Users/index.js
  src/constants/adminRoutes.js
  src/constants/navRoutes.js
  src/constants/users.js
  src/lambda/getUsers.js
Labels: awaiting-review

#63 Fix menu #61
  src/components/Common/Nav/Nav.style.js
  src/components/Legend/Legend.styles.js
  src/components/Map/Map.css
Labels: awaiting-review, in-review

#64 Fix logo sizing #62
  src/components/Admin/Dashboard/Dashboard.style.js
  src/components/PostcodeForm/PostcodeForm.styles.js
Labels: awaiting-review, in-review
